### ISSUE TITLE
why can't I use bluebird syntax on $http results?

### ISSUE THREAD

**Issue by duanefields** [mattlewis92/angular-bluebird-promises#14]
Maybe I'm missing something, but $http appears to have bluebird as its prototype when loading this module, but what can't I do this?

````coffee
    @$http.post '/accounts/authenticate', {email, password}
    .spread (data, status, headers, config) =>
      @$sessionStorage.token = data.token
      @user = jwtDecode @$sessionStorage.token
      console.log "Login successful for", @user
      @user
    .catch (err) =>
      console.log "Login failed, clearing any existing data", err
      @logout()
      throw "login failed"
````

Instead it complains about the spread expecting a thennable

**Comment by angelxmoreno** [comment]
A quick look at your code tells me you are assuming $http.post() will return an array. Could you verify this?

**Comment by mattlewis92** [comment]
@angelxmoreno is correct, .spread only works if you're returning an array. So if $http.post returned [data, status, headers, config] instead of an object then .spread would work. Instead you can either use the deprecated `.success` method or ES6 destructuring `.then({data})` (I'm not sure what the equivalent would be in coffeescript). Or just `.then(result)` and then use `result.data`.

**Comment by duanefields** [comment]
Thanks

**Comment by angelxmoreno** [comment]
:+1:
